services:
  - type: web
    name: huasteca-backend
    env: go
    plan: free
    buildCommand: "go build -o huasteca-server-prod ./cmd/server"
    startCommand: "./huasteca-server-prod"
    healthCheckPath: /health
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: PORT
        value: 8080
      - key: CORS_ORIGINS
        value: https://huasteca-angular.vercel.app
